name: Build-docs

on:
  push:
    branches:
    - main
    - staging

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash build-docs.sh
        env:
          DOCS_KEY: ${{ secrets.DOCS_KEY }}
